export default [
        {
            "team": "tottenham",
            "name": "Heung Min Son",
            "position": "LW",
            "ovr": "89",
            "pac": "88",
            "sho": "89",
            "pas": "82",
            "dri": "86",
            "def": "42",
            "phy": "69"
        },
        {
            "team": "tottenham",
            "name": "Harry Kane",
            "position": "ST",
            "ovr": "89",
            "pac": "82",
            "sho": "47",
            "pas": "82",
            "dri": "82",
            "def": "47",
            "phy": "82"
        },
        {
            "team": "tottenham",
            "name": "Hugo Lloris",
            "position": "GK",
            "ovr": "87",
            "pac": "88",
            "sho": "61",
            "pas": "84",
            "dri": "88",
            "def": "61",
            "phy": "84"
        },
        {
            "team": "tottenham",
            "name": "Ivan Perisic",
            "position": "LM",
            "ovr": "84",
            "pac": "82",
            "sho": "74",
            "pas": "78",
            "dri": "82",
            "def": "74",
            "phy": "78"
        },
        {
            "team": "tottenham",
            "name": "Pierre-Emile Hojbjerg",
            "position": "CDM",
            "ovr": "83",
            "pac": "77",
            "sho": "80",
            "pas": "82",
            "dri": "77",
            "def": "80",
            "phy": "82"
        },
        {
            "team": "tottenham",
            "name": "Cristian Romero",
            "position": "CB",
            "ovr": "83",
            "pac": "65",
            "sho": "85",
            "pas": "82",
            "dri": "65",
            "def": "85",
            "phy": "82"
        },
        {
            "team": "tottenham",
            "name": "Dejan Kulusevski",
            "position": "RW",
            "ovr": "81",
            "pac": "83",
            "sho": "56",
            "pas": "76",
            "dri": "83",
            "def": "56",
            "phy": "76"
        },
        {
            "team": "tottenham",
            "name": "Richarlison",
            "position": "ST",
            "ovr": "81",
            "pac": "82",
            "sho": "53",
            "pas": "79",
            "dri": "82",
            "def": "53",
            "phy": "79"
        },
        {
            "team": "tottenham",
            "name": "Yves Bissouma",
            "position": "CDM",
            "ovr": "81",
            "pac": "79",
            "sho": "80",
            "pas": "77",
            "dri": "79",
            "def": "80",
            "phy": "77"
        },
        {
            "team": "tottenham",
            "name": "Lucas Moura",
            "position": "RW",
            "ovr": "80",
            "pac": "85",
            "sho": "46",
            "pas": "68",
            "dri": "85",
            "def": "46",
            "phy": "68"
        },
        {
            "team": "tottenham",
            "name": "Eric Dier",
            "position": "CB",
            "ovr": "80",
            "pac": "65",
            "sho": "80",
            "pas": "84",
            "dri": "65",
            "def": "80",
            "phy": "84"
        },
        {
            "team": "tottenham",
            "name": "Ben Davies",
            "position": "CB",
            "ovr": "79",
            "pac": "72",
            "sho": "80",
            "pas": "74",
            "dri": "72",
            "def": "80",
            "phy": "74"
        },
        {
            "team": "tottenham",
            "name": "Rodrigo Bentancu",
            "position": "CM",
            "ovr": "79",
            "pac": "80",
            "sho": "78",
            "pas": "77",
            "dri": "80",
            "def": "78",
            "phy": "77"
        },
        {
            "team": "tottenham",
            "name": "Davinson Sanchez",
            "position": "CB",
            "ovr": "78",
            "pac": "66",
            "sho": "79",
            "pas": "79",
            "dri": "66",
            "def": "79",
            "phy": "79"
        },
        {
            "team": "tottenham",
            "name": "Clement Lenglet",
            "position": "CB",
            "ovr": "78",
            "pac": "64",
            "sho": "77",
            "pas": "76",
            "dri": "64",
            "def": "77",
            "phy": "76"
        },
        {
            "team": "tottenham",
            "name": "Emerson Royal",
            "position": "RWB",
            "ovr": "78",
            "pac": "74",
            "sho": "75",
            "pas": "76",
            "dri": "74",
            "def": "75",
            "phy": "76"
        },
        {
            "team": "tottenham",
            "name": "Matt Doherty",
            "position": "RWB",
            "ovr": "77",
            "pac": "73",
            "sho": "74",
            "pas": "75",
            "dri": "73",
            "def": "74",
            "phy": "75"
        },
        {
            "team": "tottenham",
            "name": "Oliver Skipp",
            "position": "CDM",
            "ovr": "77",
            "pac": "71",
            "sho": "75",
            "pas": "71",
            "dri": "71",
            "def": "75",
            "phy": "71"
        }
    ]